#name = input("Введите ваше имя: ")
#print("Привет", name)
#age = input(f"{name},Сколько вам лет: ")
#num1 = float(input("Введите первое число: "))
#num2 = float(input("Введите второе число: "))
#print()
#print("Операции с числами: ")
#print()
#print("сложение -", num1 + num2)
#print("вычитание -", num1 - num2)
#print("умножение -", num1 * num2)
#print("деление -", num1 // num2)
#P = int(input("Начальная сумма вклада:"))
#R = int(input("Процент по вкладу:"))
#T = int(input("Количество лет:"))
#print("Начисленные проценты :", (P * R * T) / 100)
#def say_hello(): print("Hello")

#say_hello()
#c = int(input("Введите температуру в градусах Цельсия:"))
#F= (9/5)*(c) + 32
#print(c,"градусов Цельсия равны", F,"градусом фаренгейта")